// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channel.proto

package seker.training.dataprocess.protobuf;

public final class ChannelProto {
  private ChannelProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ChannelOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional string title = 1;
    /**
     * <code>optional string title = 1;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 1;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 1;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // optional string link = 2;
    /**
     * <code>optional string link = 2;</code>
     */
    boolean hasLink();
    /**
     * <code>optional string link = 2;</code>
     */
    java.lang.String getLink();
    /**
     * <code>optional string link = 2;</code>
     */
    com.google.protobuf.ByteString
        getLinkBytes();

    // optional string description = 3;
    /**
     * <code>optional string description = 3;</code>
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 3;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    // optional string pubDate = 4;
    /**
     * <code>optional string pubDate = 4;</code>
     */
    boolean hasPubDate();
    /**
     * <code>optional string pubDate = 4;</code>
     */
    java.lang.String getPubDate();
    /**
     * <code>optional string pubDate = 4;</code>
     */
    com.google.protobuf.ByteString
        getPubDateBytes();

    // optional string lastBuildDate = 5;
    /**
     * <code>optional string lastBuildDate = 5;</code>
     */
    boolean hasLastBuildDate();
    /**
     * <code>optional string lastBuildDate = 5;</code>
     */
    java.lang.String getLastBuildDate();
    /**
     * <code>optional string lastBuildDate = 5;</code>
     */
    com.google.protobuf.ByteString
        getLastBuildDateBytes();

    // repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;
    /**
     * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
     */
    java.util.List<seker.training.dataprocess.protobuf.ChannelProto.Channel.Item> 
        getItemList();
    /**
     * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
     */
    seker.training.dataprocess.protobuf.ChannelProto.Channel.Item getItem(int index);
    /**
     * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
     */
    int getItemCount();
  }
  /**
   * Protobuf type {@code seker.training.dataprocess.protobuf.Channel}
   */
  public static final class Channel extends
      com.google.protobuf.GeneratedMessageLite
      implements ChannelOrBuilder {
    // Use Channel.newBuilder() to construct.
    private Channel(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private Channel(boolean noInit) {}

    private static final Channel defaultInstance;
    public static Channel getDefaultInstance() {
      return defaultInstance;
    }

    public Channel getDefaultInstanceForType() {
      return defaultInstance;
    }

    private Channel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              title_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              link_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              pubDate_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              lastBuildDate_ = input.readBytes();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                item_ = new java.util.ArrayList<seker.training.dataprocess.protobuf.ChannelProto.Channel.Item>();
                mutable_bitField0_ |= 0x00000020;
              }
              item_.add(input.readMessage(seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          item_ = java.util.Collections.unmodifiableList(item_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Channel> PARSER =
        new com.google.protobuf.AbstractParser<Channel>() {
      public Channel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Channel(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Channel> getParserForType() {
      return PARSER;
    }

    public interface ItemOrBuilder
        extends com.google.protobuf.MessageLiteOrBuilder {

      // optional string title = 1;
      /**
       * <code>optional string title = 1;</code>
       */
      boolean hasTitle();
      /**
       * <code>optional string title = 1;</code>
       */
      java.lang.String getTitle();
      /**
       * <code>optional string title = 1;</code>
       */
      com.google.protobuf.ByteString
          getTitleBytes();

      // optional string link = 2;
      /**
       * <code>optional string link = 2;</code>
       */
      boolean hasLink();
      /**
       * <code>optional string link = 2;</code>
       */
      java.lang.String getLink();
      /**
       * <code>optional string link = 2;</code>
       */
      com.google.protobuf.ByteString
          getLinkBytes();

      // optional string description = 3;
      /**
       * <code>optional string description = 3;</code>
       */
      boolean hasDescription();
      /**
       * <code>optional string description = 3;</code>
       */
      java.lang.String getDescription();
      /**
       * <code>optional string description = 3;</code>
       */
      com.google.protobuf.ByteString
          getDescriptionBytes();

      // optional string pubDate = 4;
      /**
       * <code>optional string pubDate = 4;</code>
       */
      boolean hasPubDate();
      /**
       * <code>optional string pubDate = 4;</code>
       */
      java.lang.String getPubDate();
      /**
       * <code>optional string pubDate = 4;</code>
       */
      com.google.protobuf.ByteString
          getPubDateBytes();

      // optional .seker.training.dataprocess.protobuf.Channel.Item.Guid guid = 5;
      /**
       * <code>optional .seker.training.dataprocess.protobuf.Channel.Item.Guid guid = 5;</code>
       */
      boolean hasGuid();
      /**
       * <code>optional .seker.training.dataprocess.protobuf.Channel.Item.Guid guid = 5;</code>
       */
      seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid getGuid();
    }
    /**
     * Protobuf type {@code seker.training.dataprocess.protobuf.Channel.Item}
     */
    public static final class Item extends
        com.google.protobuf.GeneratedMessageLite
        implements ItemOrBuilder {
      // Use Item.newBuilder() to construct.
      private Item(com.google.protobuf.GeneratedMessageLite.Builder builder) {
        super(builder);

      }
      private Item(boolean noInit) {}

      private static final Item defaultInstance;
      public static Item getDefaultInstance() {
        return defaultInstance;
      }

      public Item getDefaultInstanceForType() {
        return defaultInstance;
      }

      private Item(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                title_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                link_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                description_ = input.readBytes();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                pubDate_ = input.readBytes();
                break;
              }
              case 42: {
                seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid.Builder subBuilder = null;
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                  subBuilder = guid_.toBuilder();
                }
                guid_ = input.readMessage(seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(guid_);
                  guid_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000010;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static com.google.protobuf.Parser<Item> PARSER =
          new com.google.protobuf.AbstractParser<Item>() {
        public Item parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Item(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Item> getParserForType() {
        return PARSER;
      }

      public interface GuidOrBuilder
          extends com.google.protobuf.MessageLiteOrBuilder {

        // optional bool isPermaLink = 1;
        /**
         * <code>optional bool isPermaLink = 1;</code>
         */
        boolean hasIsPermaLink();
        /**
         * <code>optional bool isPermaLink = 1;</code>
         */
        boolean getIsPermaLink();

        // optional string url = 2;
        /**
         * <code>optional string url = 2;</code>
         */
        boolean hasUrl();
        /**
         * <code>optional string url = 2;</code>
         */
        java.lang.String getUrl();
        /**
         * <code>optional string url = 2;</code>
         */
        com.google.protobuf.ByteString
            getUrlBytes();
      }
      /**
       * Protobuf type {@code seker.training.dataprocess.protobuf.Channel.Item.Guid}
       */
      public static final class Guid extends
          com.google.protobuf.GeneratedMessageLite
          implements GuidOrBuilder {
        // Use Guid.newBuilder() to construct.
        private Guid(com.google.protobuf.GeneratedMessageLite.Builder builder) {
          super(builder);

        }
        private Guid(boolean noInit) {}

        private static final Guid defaultInstance;
        public static Guid getDefaultInstance() {
          return defaultInstance;
        }

        public Guid getDefaultInstanceForType() {
          return defaultInstance;
        }

        private Guid(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          initFields();
          int mutable_bitField0_ = 0;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(input,
                                         extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  isPermaLink_ = input.readBool();
                  break;
                }
                case 18: {
                  bitField0_ |= 0x00000002;
                  url_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
          } finally {
            makeExtensionsImmutable();
          }
        }
        public static com.google.protobuf.Parser<Guid> PARSER =
            new com.google.protobuf.AbstractParser<Guid>() {
          public Guid parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Guid(input, extensionRegistry);
          }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<Guid> getParserForType() {
          return PARSER;
        }

        private int bitField0_;
        // optional bool isPermaLink = 1;
        public static final int ISPERMALINK_FIELD_NUMBER = 1;
        private boolean isPermaLink_;
        /**
         * <code>optional bool isPermaLink = 1;</code>
         */
        public boolean hasIsPermaLink() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional bool isPermaLink = 1;</code>
         */
        public boolean getIsPermaLink() {
          return isPermaLink_;
        }

        // optional string url = 2;
        public static final int URL_FIELD_NUMBER = 2;
        private java.lang.Object url_;
        /**
         * <code>optional string url = 2;</code>
         */
        public boolean hasUrl() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string url = 2;</code>
         */
        public java.lang.String getUrl() {
          java.lang.Object ref = url_;
          if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              url_ = s;
            }
            return s;
          }
        }
        /**
         * <code>optional string url = 2;</code>
         */
        public com.google.protobuf.ByteString
            getUrlBytes() {
          java.lang.Object ref = url_;
          if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            url_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        private void initFields() {
          isPermaLink_ = false;
          url_ = "";
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized != -1) return isInitialized == 1;

          memoizedIsInitialized = 1;
          return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          getSerializedSize();
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeBool(1, isPermaLink_);
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            output.writeBytes(2, getUrlBytes());
          }
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
          int size = memoizedSerializedSize;
          if (size != -1) return size;

          size = 0;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += com.google.protobuf.CodedOutputStream
              .computeBoolSize(1, isPermaLink_);
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(2, getUrlBytes());
          }
          memoizedSerializedSize = size;
          return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
          return super.writeReplace();
        }

        public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return PARSER.parseFrom(input);
        }
        public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseFrom(input, extensionRegistry);
        }
        public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          return PARSER.parseDelimitedFrom(input);
        }
        public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return PARSER.parseFrom(input);
        }
        public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid prototype) {
          return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        /**
         * Protobuf type {@code seker.training.dataprocess.protobuf.Channel.Item.Guid}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
              seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid, Builder>
            implements seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.GuidOrBuilder {
          // Construct using seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }

          private void maybeForceBuilderInitialization() {
          }
          private static Builder create() {
            return new Builder();
          }

          public Builder clear() {
            super.clear();
            isPermaLink_ = false;
            bitField0_ = (bitField0_ & ~0x00000001);
            url_ = "";
            bitField0_ = (bitField0_ & ~0x00000002);
            return this;
          }

          public Builder clone() {
            return create().mergeFrom(buildPartial());
          }

          public seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid getDefaultInstanceForType() {
            return seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid.getDefaultInstance();
          }

          public seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid build() {
            seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }

          public seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid buildPartial() {
            seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid result = new seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
              to_bitField0_ |= 0x00000001;
            }
            result.isPermaLink_ = isPermaLink_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
              to_bitField0_ |= 0x00000002;
            }
            result.url_ = url_;
            result.bitField0_ = to_bitField0_;
            return result;
          }

          public Builder mergeFrom(seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid other) {
            if (other == seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid.getDefaultInstance()) return this;
            if (other.hasIsPermaLink()) {
              setIsPermaLink(other.getIsPermaLink());
            }
            if (other.hasUrl()) {
              bitField0_ |= 0x00000002;
              url_ = other.url_;
              
            }
            return this;
          }

          public final boolean isInitialized() {
            return true;
          }

          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid parsedMessage = null;
            try {
              parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              parsedMessage = (seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid) e.getUnfinishedMessage();
              throw e;
            } finally {
              if (parsedMessage != null) {
                mergeFrom(parsedMessage);
              }
            }
            return this;
          }
          private int bitField0_;

          // optional bool isPermaLink = 1;
          private boolean isPermaLink_ ;
          /**
           * <code>optional bool isPermaLink = 1;</code>
           */
          public boolean hasIsPermaLink() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
          }
          /**
           * <code>optional bool isPermaLink = 1;</code>
           */
          public boolean getIsPermaLink() {
            return isPermaLink_;
          }
          /**
           * <code>optional bool isPermaLink = 1;</code>
           */
          public Builder setIsPermaLink(boolean value) {
            bitField0_ |= 0x00000001;
            isPermaLink_ = value;
            
            return this;
          }
          /**
           * <code>optional bool isPermaLink = 1;</code>
           */
          public Builder clearIsPermaLink() {
            bitField0_ = (bitField0_ & ~0x00000001);
            isPermaLink_ = false;
            
            return this;
          }

          // optional string url = 2;
          private java.lang.Object url_ = "";
          /**
           * <code>optional string url = 2;</code>
           */
          public boolean hasUrl() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
          }
          /**
           * <code>optional string url = 2;</code>
           */
          public java.lang.String getUrl() {
            java.lang.Object ref = url_;
            if (!(ref instanceof java.lang.String)) {
              java.lang.String s = ((com.google.protobuf.ByteString) ref)
                  .toStringUtf8();
              url_ = s;
              return s;
            } else {
              return (java.lang.String) ref;
            }
          }
          /**
           * <code>optional string url = 2;</code>
           */
          public com.google.protobuf.ByteString
              getUrlBytes() {
            java.lang.Object ref = url_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
              url_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>optional string url = 2;</code>
           */
          public Builder setUrl(
              java.lang.String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
            url_ = value;
            
            return this;
          }
          /**
           * <code>optional string url = 2;</code>
           */
          public Builder clearUrl() {
            bitField0_ = (bitField0_ & ~0x00000002);
            url_ = getDefaultInstance().getUrl();
            
            return this;
          }
          /**
           * <code>optional string url = 2;</code>
           */
          public Builder setUrlBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
            url_ = value;
            
            return this;
          }

          // @@protoc_insertion_point(builder_scope:seker.training.dataprocess.protobuf.Channel.Item.Guid)
        }

        static {
          defaultInstance = new Guid(true);
          defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:seker.training.dataprocess.protobuf.Channel.Item.Guid)
      }

      private int bitField0_;
      // optional string title = 1;
      public static final int TITLE_FIELD_NUMBER = 1;
      private java.lang.Object title_;
      /**
       * <code>optional string title = 1;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string title = 1;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string link = 2;
      public static final int LINK_FIELD_NUMBER = 2;
      private java.lang.Object link_;
      /**
       * <code>optional string link = 2;</code>
       */
      public boolean hasLink() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string link = 2;</code>
       */
      public java.lang.String getLink() {
        java.lang.Object ref = link_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            link_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string link = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLinkBytes() {
        java.lang.Object ref = link_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          link_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string description = 3;
      public static final int DESCRIPTION_FIELD_NUMBER = 3;
      private java.lang.Object description_;
      /**
       * <code>optional string description = 3;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string pubDate = 4;
      public static final int PUBDATE_FIELD_NUMBER = 4;
      private java.lang.Object pubDate_;
      /**
       * <code>optional string pubDate = 4;</code>
       */
      public boolean hasPubDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string pubDate = 4;</code>
       */
      public java.lang.String getPubDate() {
        java.lang.Object ref = pubDate_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pubDate_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string pubDate = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPubDateBytes() {
        java.lang.Object ref = pubDate_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pubDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional .seker.training.dataprocess.protobuf.Channel.Item.Guid guid = 5;
      public static final int GUID_FIELD_NUMBER = 5;
      private seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid guid_;
      /**
       * <code>optional .seker.training.dataprocess.protobuf.Channel.Item.Guid guid = 5;</code>
       */
      public boolean hasGuid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .seker.training.dataprocess.protobuf.Channel.Item.Guid guid = 5;</code>
       */
      public seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid getGuid() {
        return guid_;
      }

      private void initFields() {
        title_ = "";
        link_ = "";
        description_ = "";
        pubDate_ = "";
        guid_ = seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid.getDefaultInstance();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getTitleBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getLinkBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getDescriptionBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getPubDateBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeMessage(5, guid_);
        }
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getTitleBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getLinkBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getDescriptionBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getPubDateBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, guid_);
        }
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static seker.training.dataprocess.protobuf.ChannelProto.Channel.Item parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(seker.training.dataprocess.protobuf.ChannelProto.Channel.Item prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      /**
       * Protobuf type {@code seker.training.dataprocess.protobuf.Channel.Item}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            seker.training.dataprocess.protobuf.ChannelProto.Channel.Item, Builder>
          implements seker.training.dataprocess.protobuf.ChannelProto.Channel.ItemOrBuilder {
        // Construct using seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          title_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          link_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          description_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          pubDate_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          guid_ = seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid.getDefaultInstance();
          bitField0_ = (bitField0_ & ~0x00000010);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public seker.training.dataprocess.protobuf.ChannelProto.Channel.Item getDefaultInstanceForType() {
          return seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.getDefaultInstance();
        }

        public seker.training.dataprocess.protobuf.ChannelProto.Channel.Item build() {
          seker.training.dataprocess.protobuf.ChannelProto.Channel.Item result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public seker.training.dataprocess.protobuf.ChannelProto.Channel.Item buildPartial() {
          seker.training.dataprocess.protobuf.ChannelProto.Channel.Item result = new seker.training.dataprocess.protobuf.ChannelProto.Channel.Item(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.title_ = title_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.link_ = link_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.description_ = description_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.pubDate_ = pubDate_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.guid_ = guid_;
          result.bitField0_ = to_bitField0_;
          return result;
        }

        public Builder mergeFrom(seker.training.dataprocess.protobuf.ChannelProto.Channel.Item other) {
          if (other == seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.getDefaultInstance()) return this;
          if (other.hasTitle()) {
            bitField0_ |= 0x00000001;
            title_ = other.title_;
            
          }
          if (other.hasLink()) {
            bitField0_ |= 0x00000002;
            link_ = other.link_;
            
          }
          if (other.hasDescription()) {
            bitField0_ |= 0x00000004;
            description_ = other.description_;
            
          }
          if (other.hasPubDate()) {
            bitField0_ |= 0x00000008;
            pubDate_ = other.pubDate_;
            
          }
          if (other.hasGuid()) {
            mergeGuid(other.getGuid());
          }
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          seker.training.dataprocess.protobuf.ChannelProto.Channel.Item parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (seker.training.dataprocess.protobuf.ChannelProto.Channel.Item) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string title = 1;
        private java.lang.Object title_ = "";
        /**
         * <code>optional string title = 1;</code>
         */
        public boolean hasTitle() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string title = 1;</code>
         */
        public java.lang.String getTitle() {
          java.lang.Object ref = title_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            title_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string title = 1;</code>
         */
        public com.google.protobuf.ByteString
            getTitleBytes() {
          java.lang.Object ref = title_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            title_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string title = 1;</code>
         */
        public Builder setTitle(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          title_ = value;
          
          return this;
        }
        /**
         * <code>optional string title = 1;</code>
         */
        public Builder clearTitle() {
          bitField0_ = (bitField0_ & ~0x00000001);
          title_ = getDefaultInstance().getTitle();
          
          return this;
        }
        /**
         * <code>optional string title = 1;</code>
         */
        public Builder setTitleBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          title_ = value;
          
          return this;
        }

        // optional string link = 2;
        private java.lang.Object link_ = "";
        /**
         * <code>optional string link = 2;</code>
         */
        public boolean hasLink() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string link = 2;</code>
         */
        public java.lang.String getLink() {
          java.lang.Object ref = link_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            link_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string link = 2;</code>
         */
        public com.google.protobuf.ByteString
            getLinkBytes() {
          java.lang.Object ref = link_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            link_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string link = 2;</code>
         */
        public Builder setLink(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          link_ = value;
          
          return this;
        }
        /**
         * <code>optional string link = 2;</code>
         */
        public Builder clearLink() {
          bitField0_ = (bitField0_ & ~0x00000002);
          link_ = getDefaultInstance().getLink();
          
          return this;
        }
        /**
         * <code>optional string link = 2;</code>
         */
        public Builder setLinkBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          link_ = value;
          
          return this;
        }

        // optional string description = 3;
        private java.lang.Object description_ = "";
        /**
         * <code>optional string description = 3;</code>
         */
        public boolean hasDescription() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string description = 3;</code>
         */
        public java.lang.String getDescription() {
          java.lang.Object ref = description_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            description_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string description = 3;</code>
         */
        public com.google.protobuf.ByteString
            getDescriptionBytes() {
          java.lang.Object ref = description_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            description_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string description = 3;</code>
         */
        public Builder setDescription(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          description_ = value;
          
          return this;
        }
        /**
         * <code>optional string description = 3;</code>
         */
        public Builder clearDescription() {
          bitField0_ = (bitField0_ & ~0x00000004);
          description_ = getDefaultInstance().getDescription();
          
          return this;
        }
        /**
         * <code>optional string description = 3;</code>
         */
        public Builder setDescriptionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          description_ = value;
          
          return this;
        }

        // optional string pubDate = 4;
        private java.lang.Object pubDate_ = "";
        /**
         * <code>optional string pubDate = 4;</code>
         */
        public boolean hasPubDate() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional string pubDate = 4;</code>
         */
        public java.lang.String getPubDate() {
          java.lang.Object ref = pubDate_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            pubDate_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string pubDate = 4;</code>
         */
        public com.google.protobuf.ByteString
            getPubDateBytes() {
          java.lang.Object ref = pubDate_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            pubDate_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string pubDate = 4;</code>
         */
        public Builder setPubDate(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          pubDate_ = value;
          
          return this;
        }
        /**
         * <code>optional string pubDate = 4;</code>
         */
        public Builder clearPubDate() {
          bitField0_ = (bitField0_ & ~0x00000008);
          pubDate_ = getDefaultInstance().getPubDate();
          
          return this;
        }
        /**
         * <code>optional string pubDate = 4;</code>
         */
        public Builder setPubDateBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          pubDate_ = value;
          
          return this;
        }

        // optional .seker.training.dataprocess.protobuf.Channel.Item.Guid guid = 5;
        private seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid guid_ = seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid.getDefaultInstance();
        /**
         * <code>optional .seker.training.dataprocess.protobuf.Channel.Item.Guid guid = 5;</code>
         */
        public boolean hasGuid() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional .seker.training.dataprocess.protobuf.Channel.Item.Guid guid = 5;</code>
         */
        public seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid getGuid() {
          return guid_;
        }
        /**
         * <code>optional .seker.training.dataprocess.protobuf.Channel.Item.Guid guid = 5;</code>
         */
        public Builder setGuid(seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid value) {
          if (value == null) {
            throw new NullPointerException();
          }
          guid_ = value;

          bitField0_ |= 0x00000010;
          return this;
        }
        /**
         * <code>optional .seker.training.dataprocess.protobuf.Channel.Item.Guid guid = 5;</code>
         */
        public Builder setGuid(
            seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid.Builder builderForValue) {
          guid_ = builderForValue.build();

          bitField0_ |= 0x00000010;
          return this;
        }
        /**
         * <code>optional .seker.training.dataprocess.protobuf.Channel.Item.Guid guid = 5;</code>
         */
        public Builder mergeGuid(seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid value) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              guid_ != seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid.getDefaultInstance()) {
            guid_ =
              seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid.newBuilder(guid_).mergeFrom(value).buildPartial();
          } else {
            guid_ = value;
          }

          bitField0_ |= 0x00000010;
          return this;
        }
        /**
         * <code>optional .seker.training.dataprocess.protobuf.Channel.Item.Guid guid = 5;</code>
         */
        public Builder clearGuid() {
          guid_ = seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Guid.getDefaultInstance();

          bitField0_ = (bitField0_ & ~0x00000010);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:seker.training.dataprocess.protobuf.Channel.Item)
      }

      static {
        defaultInstance = new Item(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:seker.training.dataprocess.protobuf.Channel.Item)
    }

    private int bitField0_;
    // optional string title = 1;
    public static final int TITLE_FIELD_NUMBER = 1;
    private java.lang.Object title_;
    /**
     * <code>optional string title = 1;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string title = 1;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string link = 2;
    public static final int LINK_FIELD_NUMBER = 2;
    private java.lang.Object link_;
    /**
     * <code>optional string link = 2;</code>
     */
    public boolean hasLink() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string link = 2;</code>
     */
    public java.lang.String getLink() {
      java.lang.Object ref = link_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          link_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string link = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLinkBytes() {
      java.lang.Object ref = link_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        link_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    /**
     * <code>optional string description = 3;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string pubDate = 4;
    public static final int PUBDATE_FIELD_NUMBER = 4;
    private java.lang.Object pubDate_;
    /**
     * <code>optional string pubDate = 4;</code>
     */
    public boolean hasPubDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string pubDate = 4;</code>
     */
    public java.lang.String getPubDate() {
      java.lang.Object ref = pubDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pubDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pubDate = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPubDateBytes() {
      java.lang.Object ref = pubDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pubDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string lastBuildDate = 5;
    public static final int LASTBUILDDATE_FIELD_NUMBER = 5;
    private java.lang.Object lastBuildDate_;
    /**
     * <code>optional string lastBuildDate = 5;</code>
     */
    public boolean hasLastBuildDate() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string lastBuildDate = 5;</code>
     */
    public java.lang.String getLastBuildDate() {
      java.lang.Object ref = lastBuildDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastBuildDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lastBuildDate = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLastBuildDateBytes() {
      java.lang.Object ref = lastBuildDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastBuildDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;
    public static final int ITEM_FIELD_NUMBER = 6;
    private java.util.List<seker.training.dataprocess.protobuf.ChannelProto.Channel.Item> item_;
    /**
     * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
     */
    public java.util.List<seker.training.dataprocess.protobuf.ChannelProto.Channel.Item> getItemList() {
      return item_;
    }
    /**
     * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
     */
    public java.util.List<? extends seker.training.dataprocess.protobuf.ChannelProto.Channel.ItemOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
     */
    public seker.training.dataprocess.protobuf.ChannelProto.Channel.Item getItem(int index) {
      return item_.get(index);
    }
    /**
     * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
     */
    public seker.training.dataprocess.protobuf.ChannelProto.Channel.ItemOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }

    private void initFields() {
      title_ = "";
      link_ = "";
      description_ = "";
      pubDate_ = "";
      lastBuildDate_ = "";
      item_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTitleBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLinkBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPubDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getLastBuildDateBytes());
      }
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(6, item_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTitleBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLinkBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPubDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getLastBuildDateBytes());
      }
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, item_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static seker.training.dataprocess.protobuf.ChannelProto.Channel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seker.training.dataprocess.protobuf.ChannelProto.Channel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seker.training.dataprocess.protobuf.ChannelProto.Channel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static seker.training.dataprocess.protobuf.ChannelProto.Channel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static seker.training.dataprocess.protobuf.ChannelProto.Channel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static seker.training.dataprocess.protobuf.ChannelProto.Channel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static seker.training.dataprocess.protobuf.ChannelProto.Channel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static seker.training.dataprocess.protobuf.ChannelProto.Channel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static seker.training.dataprocess.protobuf.ChannelProto.Channel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static seker.training.dataprocess.protobuf.ChannelProto.Channel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(seker.training.dataprocess.protobuf.ChannelProto.Channel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code seker.training.dataprocess.protobuf.Channel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          seker.training.dataprocess.protobuf.ChannelProto.Channel, Builder>
        implements seker.training.dataprocess.protobuf.ChannelProto.ChannelOrBuilder {
      // Construct using seker.training.dataprocess.protobuf.ChannelProto.Channel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        link_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        pubDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        lastBuildDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        item_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public seker.training.dataprocess.protobuf.ChannelProto.Channel getDefaultInstanceForType() {
        return seker.training.dataprocess.protobuf.ChannelProto.Channel.getDefaultInstance();
      }

      public seker.training.dataprocess.protobuf.ChannelProto.Channel build() {
        seker.training.dataprocess.protobuf.ChannelProto.Channel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public seker.training.dataprocess.protobuf.ChannelProto.Channel buildPartial() {
        seker.training.dataprocess.protobuf.ChannelProto.Channel result = new seker.training.dataprocess.protobuf.ChannelProto.Channel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.link_ = link_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pubDate_ = pubDate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.lastBuildDate_ = lastBuildDate_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          item_ = java.util.Collections.unmodifiableList(item_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.item_ = item_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(seker.training.dataprocess.protobuf.ChannelProto.Channel other) {
        if (other == seker.training.dataprocess.protobuf.ChannelProto.Channel.getDefaultInstance()) return this;
        if (other.hasTitle()) {
          bitField0_ |= 0x00000001;
          title_ = other.title_;
          
        }
        if (other.hasLink()) {
          bitField0_ |= 0x00000002;
          link_ = other.link_;
          
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000004;
          description_ = other.description_;
          
        }
        if (other.hasPubDate()) {
          bitField0_ |= 0x00000008;
          pubDate_ = other.pubDate_;
          
        }
        if (other.hasLastBuildDate()) {
          bitField0_ |= 0x00000010;
          lastBuildDate_ = other.lastBuildDate_;
          
        }
        if (!other.item_.isEmpty()) {
          if (item_.isEmpty()) {
            item_ = other.item_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureItemIsMutable();
            item_.addAll(other.item_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        seker.training.dataprocess.protobuf.ChannelProto.Channel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (seker.training.dataprocess.protobuf.ChannelProto.Channel) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string title = 1;
      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 1;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string title = 1;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 1;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
        
        return this;
      }
      /**
       * <code>optional string title = 1;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = getDefaultInstance().getTitle();
        
        return this;
      }
      /**
       * <code>optional string title = 1;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
        
        return this;
      }

      // optional string link = 2;
      private java.lang.Object link_ = "";
      /**
       * <code>optional string link = 2;</code>
       */
      public boolean hasLink() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string link = 2;</code>
       */
      public java.lang.String getLink() {
        java.lang.Object ref = link_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          link_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string link = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLinkBytes() {
        java.lang.Object ref = link_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          link_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string link = 2;</code>
       */
      public Builder setLink(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        link_ = value;
        
        return this;
      }
      /**
       * <code>optional string link = 2;</code>
       */
      public Builder clearLink() {
        bitField0_ = (bitField0_ & ~0x00000002);
        link_ = getDefaultInstance().getLink();
        
        return this;
      }
      /**
       * <code>optional string link = 2;</code>
       */
      public Builder setLinkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        link_ = value;
        
        return this;
      }

      // optional string description = 3;
      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 3;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        
        return this;
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        
        return this;
      }
      /**
       * <code>optional string description = 3;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        
        return this;
      }

      // optional string pubDate = 4;
      private java.lang.Object pubDate_ = "";
      /**
       * <code>optional string pubDate = 4;</code>
       */
      public boolean hasPubDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string pubDate = 4;</code>
       */
      public java.lang.String getPubDate() {
        java.lang.Object ref = pubDate_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pubDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pubDate = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPubDateBytes() {
        java.lang.Object ref = pubDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pubDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pubDate = 4;</code>
       */
      public Builder setPubDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        pubDate_ = value;
        
        return this;
      }
      /**
       * <code>optional string pubDate = 4;</code>
       */
      public Builder clearPubDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pubDate_ = getDefaultInstance().getPubDate();
        
        return this;
      }
      /**
       * <code>optional string pubDate = 4;</code>
       */
      public Builder setPubDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        pubDate_ = value;
        
        return this;
      }

      // optional string lastBuildDate = 5;
      private java.lang.Object lastBuildDate_ = "";
      /**
       * <code>optional string lastBuildDate = 5;</code>
       */
      public boolean hasLastBuildDate() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string lastBuildDate = 5;</code>
       */
      public java.lang.String getLastBuildDate() {
        java.lang.Object ref = lastBuildDate_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          lastBuildDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lastBuildDate = 5;</code>
       */
      public com.google.protobuf.ByteString
          getLastBuildDateBytes() {
        java.lang.Object ref = lastBuildDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastBuildDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lastBuildDate = 5;</code>
       */
      public Builder setLastBuildDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        lastBuildDate_ = value;
        
        return this;
      }
      /**
       * <code>optional string lastBuildDate = 5;</code>
       */
      public Builder clearLastBuildDate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lastBuildDate_ = getDefaultInstance().getLastBuildDate();
        
        return this;
      }
      /**
       * <code>optional string lastBuildDate = 5;</code>
       */
      public Builder setLastBuildDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        lastBuildDate_ = value;
        
        return this;
      }

      // repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;
      private java.util.List<seker.training.dataprocess.protobuf.ChannelProto.Channel.Item> item_ =
        java.util.Collections.emptyList();
      private void ensureItemIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          item_ = new java.util.ArrayList<seker.training.dataprocess.protobuf.ChannelProto.Channel.Item>(item_);
          bitField0_ |= 0x00000020;
         }
      }

      /**
       * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
       */
      public java.util.List<seker.training.dataprocess.protobuf.ChannelProto.Channel.Item> getItemList() {
        return java.util.Collections.unmodifiableList(item_);
      }
      /**
       * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
       */
      public int getItemCount() {
        return item_.size();
      }
      /**
       * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
       */
      public seker.training.dataprocess.protobuf.ChannelProto.Channel.Item getItem(int index) {
        return item_.get(index);
      }
      /**
       * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
       */
      public Builder setItem(
          int index, seker.training.dataprocess.protobuf.ChannelProto.Channel.Item value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemIsMutable();
        item_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
       */
      public Builder setItem(
          int index, seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Builder builderForValue) {
        ensureItemIsMutable();
        item_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
       */
      public Builder addItem(seker.training.dataprocess.protobuf.ChannelProto.Channel.Item value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemIsMutable();
        item_.add(value);

        return this;
      }
      /**
       * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
       */
      public Builder addItem(
          int index, seker.training.dataprocess.protobuf.ChannelProto.Channel.Item value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemIsMutable();
        item_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
       */
      public Builder addItem(
          seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Builder builderForValue) {
        ensureItemIsMutable();
        item_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
       */
      public Builder addItem(
          int index, seker.training.dataprocess.protobuf.ChannelProto.Channel.Item.Builder builderForValue) {
        ensureItemIsMutable();
        item_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
       */
      public Builder addAllItem(
          java.lang.Iterable<? extends seker.training.dataprocess.protobuf.ChannelProto.Channel.Item> values) {
        ensureItemIsMutable();
        super.addAll(values, item_);

        return this;
      }
      /**
       * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
       */
      public Builder clearItem() {
        item_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);

        return this;
      }
      /**
       * <code>repeated .seker.training.dataprocess.protobuf.Channel.Item item = 6;</code>
       */
      public Builder removeItem(int index) {
        ensureItemIsMutable();
        item_.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:seker.training.dataprocess.protobuf.Channel)
    }

    static {
      defaultInstance = new Channel(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:seker.training.dataprocess.protobuf.Channel)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
